### ISSUE TITLE
gc implementation with `ext_alloc_free` 

### ISSUE THREAD

**Issue by failfmi** [LimeChain/gosemble#194]
Current GC implementation does not free memory during execution. Instead, it depends that it is freed by the host at the end of the execution.
Create a GC that collects garbage during execution and uses the host imported allocator function `ext_alloc_free`.

**PR** https://github.com/LimeChain/tinygo/pull/22

**Comment by radkomih** [comment]
```
currrent (leaking) GC
ok  	github.com/LimeChain/gosemble/runtime	6.800s
Type: wasm
Size: 525.8 KB

---

new (actual) GC
ok  	github.com/LimeChain/gosemble/runtime	12.274s
Type: wasm
Size: 713.9 KB
```
