### ISSUE TITLE
Unit tests - M1 - types

### ISSUE THREAD

**Issue by Kirqkas** [LimeChain/gosemble#216]
Add  tests for primitive types https://github.com/LimeChain/gosemble/tree/develop/primitives/types

* [x] AccountData - @radkomih 
* [x] AccountInfo - @radkomih 
* [x] ApiItem - @failfmi 
* [x] ApplyExtrinsicResult - @radkomih 
* [x] ArithmeticError - @radkomih 
* [x] Authority - @radkomih 
* [x] BalanceStatus - @radkomih 
* [x] BlockLength - @radkomih 
* [x] BlockWeights - @radkomih 
* [x] Weight - @radkomih 
* [x] DispatchOutcome - @failfmi 
* [x] FeeDetails - @radkomih 
* [x] InclusionFee - @radkomih 
* [x] Callable - @radkomih 
* [x] CheckInherentsResult - @radkomih 
* [x] InherentError - @radkomih 
* [x] DigestItem - @radkomih 
* [x] Digest - @radkomih 
* [x] DispatchClass - @radkomih 
* [x] PerDispatchClass - @radkomih 
* [x] DispatchInfo - @radkomih 
* [x] ConsumedWeight - @radkomih 
* [x] DispatchResult - @radkomih
* [x] DispatchResultWithPostInfo - @radkomih 
* [x] Event - @radkomih  
* [x] Era - @radkomih 
* [x] ExtrinsicPhase - @failfmi
* [x] SignedExtra - @radkomih 
* [x] SignedPayload - @radkomih 
* [x] ExtrinsicSignature - @radkomih 
* [x] H256, H512, Blake2bHash - @nicksinch 
* [x] Header - @nicksinch 
* [x] Identity fee - @failfmi
* [x] InherentData - @failfmi 
* [x] Invalid transaction - @failfmi
* [x] Last runtime upgrade info - @failfmi
* [x] Lookup - @nicksinch 
* [ ] Metadata
* [x] Module - @nicksinch 
* [x] Multi-address - @radkomih 
* [x] MultiSignature - @failfmi
* [x] Pays - @failfmi
* [ ] PerThings
* [x] PostDispatchInfo - @failfmi
* [x] PublicKey - @failfmi
* [x] RawOrigin - @failfmi  
* [x] RuntimeDbWeight - @failfmi 
* [x] RuntimeDIspatchInfo - @failfmi 
* [x] RuntimeVersion - @failfmi 
* [x] SessionKey - @failfmi  
* [x] SignatureEcdsa - @failfmi  
* [x] SignatureEd25519 - @failfmi  
* [x] SignatureSr25519 - @failfmi  
* [x] TimestampError - @failfmi  
* [x] TokenError - @failfmi 
* [x] TransactionOutcome - @failfmi
* [x] TransactionSource - @failfmi
* [x] TransactionValidityError - @failfmi
* [x] TransactionValidityResult - @failfmi
* [x] TransactionalError - @failfmi
* [x] UnknownTransaction - @failfmi
* [x] ValidTransaction - @failfmi
* [x] VersionedAuthorityList - @failfmi
* [x] WeightPerClass - @failfmi

**Comment by failfmi** [comment]
PerThings works as percentage
Metadata - will probably be refactored
