### ISSUE TITLE
implement the Error interface

### ISSUE THREAD

**Issue by radkomih** [LimeChain/gosemble#271]
There are places where we return values such as for eaxmple `(Address32, TransactionValidityError)`, but there may be other errors that could occur and we might want to propagate them as well. For this reason, we might consider implementing the `Error` interface for all types that resemble errors (`TransactionValidityError`, `TokenError`, etc.). 
In certain places, we should check if the error is of the type in which we are interested.

**Comment by tgntr** [comment]
as a next step we could remove Result types  (e.g. goscale.Result, DispatchResultWithPostInfo)
