### ISSUE TITLE
Gossamer modifications for benchmarking

### ISSUE THREAD

**Issue by Kirqkas** [LimeChain/gosemble#323]
* [x] Implement helper benchmarking instance with an in-memory DB (as in integration tests)
* [x] Implement mechanism for tracking the reads/writes (based on the number of keys modified by the host storage functions)
* [x] whitelist of keys to ignore for counting
* [x] implement and expose host functions: time, db r/w, whitelist keys,  commit, rollback
* [x] set min/max heap pages to 4096

**Comment by radkomih** [comment]
PR: https://github.com/LimeChain/gossamer/pull/12
