### ISSUE TITLE
why Gosemble runtime integrated in Substrate requires to grow the memory

### ISSUE THREAD

**Issue by radkomih** [LimeChain/gosemble#7]
* [ ] why Gosemble runtime integrated in Substrate [requires](https://github.com/LimeChain/substrate/blob/feat/runtime/gosemble/client/executor/common/src/runtime_blob/runtime_blob.rs#L188) to grow the memory when its given 2048 pages?
* [ ] `heap_start` for Gosemble runtime in Substrate Host - [here](https://github.com/LimeChain/substrate/blob/feat/runtime/gosemble/client/executor/wasmtime/src/runtime.rs#L208)

**Comment by failfmi** [comment]
Old issue, was with runtime which was pre-GC leaking
